"""Add extraction metadata to attachments

Revision ID: 3f806b75a7bc
Revises: 5b105000286d
Create Date: 2026-09-30 08:18:53.325160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f806b75a7bc'
down_revision: Union[str, None] = '5b105000286d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('extraction_method', sa.String(length=20), nullable=True))
    op.add_column('attachments', sa.Column('extraction_confidence', sa.Float(), nullable=True))
    op.add_column('attachments', sa.Column('text_confirmed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'text_confirmed')
    op.drop_column('attachments', 'extraction_confidence')
    op.drop_column('attachments', 'extraction_method')
    # ### end Alembic commands ###
