"""Add attachments table

Revision ID: 5b105000286d
Revises: d087ad69daed
Create Date: 2026-09-26 19:23:40.522471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b105000286d'
down_revision: Union[str, None] = 'd087ad69daed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('memory_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_backend', sa.String(length=30), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_memory_id'), 'attachments', ['memory_id'], unique=False)
    op.create_index(op.f('ix_attachments_sha256'), 'attachments', ['sha256'], unique=False)
    op.add_column('evidence', sa.Column('attachment_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'evidence', 'attachments', ['attachment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.drop_column('evidence', 'attachment_id')
    op.drop_index(op.f('ix_attachments_sha256'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_memory_id'), table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
